---
title: "p8105_hw5_sm4993"
author: "Sydney Musick"
output: github_document
---

# Problem 1

```{r load packages}
library(tidyverse)
```

```{r 1p1}
homicide_df = 
  read.csv("homicide-data.csv", na = c("", "Unknown")) %>%
  mutate(
    city_state = str_c(city, state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~"unsolved",
      disposition == "Closed by arrest" ~"solved"
    )) %>%
  relocate(city_state) %>%
  filter(city_state != "TulsaAL")              
```

```{r 1p2}
baltimore_df =
  homicide_df %>%
  filter(city_state == "BaltimoreMD")

baltimore_summary = 
  baltimore_df %>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n())

baltimore_test =
  prop.test(
    x = baltimore_summary %>% pull(unsolved), 
    n = baltimore_summary %>% pull(n))

baltimore_test %>%
  broom::tidy()
```

```{r 1p3}
prop_test_function = function(city_df) {

city_summary = 
  city_df %>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n())

city_test =
  prop.test(
    x = city_summary %>% pull(unsolved), 
    n = city_summary %>% pull(n))

return(city_test)

}

prop_test_function(baltimore_df)
```

```{r 1p4}
results_df = 
  homicide_df %>%
  nest(data = uid:resolution) %>%
  mutate(
    test_results = map(data, prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>%
  select(city_state, tidy_results) %>%
  unnest(tidy_results) %>%
  select(city_state, estimate, starts_with("conf"))

results_df
```

```{r 1p5}
results_df %>%
  mutate(city_state = fct_reorder(city_state, estimate)) %>%
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

# Problem 2

## Data import and cleaning
```{r 2p1}
zip = 
  tibble(files = 
    list.files("p8105_hw5_sm4993_files/data/", full.names = TRUE)) %>%
  mutate(data = map(files, read_csv)) %>% 
  unnest(data) %>% 
  mutate(
    exp_arm = substr(files, 30, 32),
    id = substr(files, 30, 35)) %>% 
  select(everything(), -files) %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "value")

knitr::kable(zip)
```

## Data plot
```{r 2p2}
ggplot(zip, aes(x = week, y = value, group = id, color = exp_arm)) + geom_line()
```

The control arm and the experimental treatment arm appear to have the same starting values, more or less. However, over time the control arm's values stay the same (perhaps decrease a tiny bit), while the experimental arm's values increase greatly. 

# Problem 3

## Loading data
```{r 3p1}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

## Cleaning data
```{r 3p2}
iris_function = function(x){
  if (is.character(x)) {
       x = replace_na(x, "virginica")}
  else if (is.numeric(x)) {
    x = replace_na(x, mean(x, na.rm = TRUE))}}

iris_no_missing = 
  as.data.frame(map(iris_with_missing, iris_function))

knitr::kable(iris_no_missing)
```

 